/*
 * Micro QuickJS Javascript Engine
 *
 * Copyright (c) 2017-2025 Fabrice Bellard
 * Copyright (c) 2017-2025 Charlie Gordon
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
#include <stdlib.h>
#include <stdio.h>
#include <stdarg.h>
#include <inttypes.h>
#include <string.h>
#include <assert.h>
#include <math.h>
#include <setjmp.h>

#include "cutils.h"
#include "dtoa.h"
#include "mquickjs_priv.h"

/*
  TODO:
  - regexp: better error position info
  - use a specific MTAG for short functions instead of an immediate value
  - use hash table for atoms
  - set the length accessors as non configurable so that the
    'get_length' instruction optimizations are always safe.
  - memory:
    - fix stack_bottom logic
    - launch gc at regular intervals
    - only launch compaction when needed (handle free blocks in malloc())
    - avoid pass to rehash the properties
    - ensure no undefined bytes (e.g. at end of JSString) in
      saved bytecode ?
  - reduced memory usage:
    - reduce JSFunctionBytecode size (remove source_pos)
    - do not explicitly store function names for get/set/bound
    - use JSSTDLibraryDef fields instead of copying them to JSContext ?
*/

#define __exception __attribute__((warn_unused_result))

#define JS_STACK_SLACK  16   /* additional free space on the stack */
/* min free size in bytes between heap_free and the bottom of the stack */
#define JS_MIN_FREE_SIZE 512
/* minimum free size in bytes to create the out of memory object */
#define JS_MIN_CRITICAL_FREE_SIZE (JS_MIN_FREE_SIZE - 256)
#define JS_MAX_LOCAL_VARS 65535
#define JS_MAX_FUNC_STACK_SIZE 65535
#define JS_MAX_ARGC 65535
/* maximum number of recursing JS_Call() */
#define JS_MAX_CALL_RECURSE 8


#define JS_VALUE_IS_BOTH_INT(a, b) ((((a) | (b)) & 1) == 0)
#define JS_VALUE_IS_BOTH_SHORT_FLOAT(a, b) (((((a) - JS_TAG_SHORT_FLOAT) | ((b) - JS_TAG_SHORT_FLOAT)) & 7) == 0)


/* function call flags (max 31 bits) */
#define FRAME_CF_ARGC_MASK      0xffff
/* FRAME_CF_CTOR */
#define FRAME_CF_POP_RET        (1 << 17) /* pop the return value */
#define FRAME_CF_PC_ADD1        (1 << 18) /* increment the PC by 1 instead of 3 */

#define JS_MB_PAD(n)  (JSW * 8 - (n))

typedef struct {
    JS_MB_HEADER;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS);
} JSMemBlockHeader;

typedef struct {
    JS_MB_HEADER;
    /* in JSWords excluding the header. Free blocks of JSW bytes
       are only generated by js_shrink() and may not be always
       compacted */
    JSWord size: JS_MB_PAD(JS_MTAG_BITS);
} JSFreeBlock;

#if JSW == 8
#define JS_STRING_LEN_MAX 0x7ffffffe
#else
#define JS_STRING_LEN_MAX ((1 << (32 - JS_MTAG_BITS - 3)) - 1)
#endif

typedef struct {
    JS_MB_HEADER;
    JSWord is_unique: 1;
    JSWord is_ascii: 1;
    /* true if the string content represents a number, only meaningful
       is is_unique = true */
    JSWord is_numeric: 1;
    JSWord len: JS_MB_PAD(JS_MTAG_BITS + 3);
    uint8_t buf[];
} JSString;

typedef struct {
    JSWord string_buf[sizeof(JSString) / sizeof(JSWord)]; /* for JSString */
    uint8_t buf[5];
} JSStringCharBuf;

#define JS_BYTE_ARRAY_SIZE_MAX ((1 << (32 - JS_MTAG_BITS)) - 1)

typedef struct {
    JS_MB_HEADER;
    JSWord size: JS_MB_PAD(JS_MTAG_BITS);
    uint8_t buf[];
} JSByteArray;

#define JS_VALUE_ARRAY_SIZE_MAX ((1 << (32 - JS_MTAG_BITS)) - 1)

typedef struct {
    JS_MB_HEADER;
    JSWord size: JS_MB_PAD(JS_MTAG_BITS);
    JSValue arr[];
} JSValueArray;

typedef struct JSVarRef {
    JS_MB_HEADER;
    JSWord is_detached : 1;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS + 1);
    union {
        JSValue value; /* is_detached = true */
        struct {
            JSValue next; /* is_detached = false: JS_NULL or JSVarRef,
                             must be at the same address as 'value' */
            JSValue *pvalue;
        };
    } u;
} JSVarRef;

typedef struct {
    JS_MB_HEADER;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS);
#ifdef JS_PTR64
    struct {
        double dval;
    } u;
#else
    /* unaligned 64 bit access in 32-bit mode */
    struct __attribute__((packed)) {
        double dval;
    } u;
#endif
} JSFloat64;

typedef struct JSROMClass {
    JS_MB_HEADER;
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS);
    JSValue props;
    int32_t ctor_idx; /* -1 if defining a normal object */
    JSValue proto_props;
    JSValue parent_class; /* JSROMClass or JS_NULL */
} JSROMClass;

#define N_ROM_ATOM_TABLES_MAX 2

/* must be large enough to have a negligible runtime cost and small
   enough to call the interrupt callback often. */
#define JS_INTERRUPT_COUNTER_INIT 10000

#define JS_STRING_POS_CACHE_SIZE 2
#define JS_STRING_POS_CACHE_MIN_LEN 16 

typedef enum {
    POS_TYPE_UTF8,
    POS_TYPE_UTF16,
} StringPosTypeEnum;

typedef struct {
    JSValue str; /* JS_NULL or weak reference to a JSString. It
                    contains at least JS_STRING_POS_CACHE_MIN_LEN
                    bytes and is a non ascii string */
    uint32_t str_pos[2]; /* 0 = UTF-8 pos (in bytes), 1 = UTF-16 pos */
} JSStringPosCacheEntry;

struct JSContext {
    /* memory map:
       Stack
       Free area
       Heap
       JSContext
    */
    uint8_t *heap_base;
    uint8_t *heap_free; /* first free area */
    uint8_t *stack_top;
    JSValue *stack_bottom; /* sp must always be higher than stack_bottom */
    JSValue *sp; /* current stack pointer */
    JSValue *fp; /* current frame pointer, stack_top if none */
    uint32_t min_free_size; /* min free size between heap_free and the
                               bottom of the stack */
    BOOL in_out_of_memory : 8; /* != 0 if generating the out of memory object */
    uint8_t n_rom_atom_tables;
    uint8_t string_pos_cache_counter; /* used for string_pos_cache[] update */
    uint16_t class_count; /* number of classes including user classes */
    int16_t interrupt_counter;
    BOOL current_exception_is_uncatchable : 8;
    struct JSParseState *parse_state; /* != NULL during JS_Eval() */
    int unique_strings_len;
    int js_call_rec_count; /* number of recursing JS_Call() */
    JSGCRef *top_gc_ref; /* used to reference temporary GC roots (stack top) */
    JSGCRef *last_gc_ref; /* used to reference temporary GC roots (list) */
    const JSWord *atom_table; /* constant atom table */
    /* 'n_rom_atom_tables' atom tables from code loaded from rom */
    const JSValueArray *rom_atom_tables[N_ROM_ATOM_TABLES_MAX];
    const JSCFunctionDef *c_function_table;
    const JSCFinalizer *c_finalizer_table;
    uint64_t random_state;
    JSInterruptHandler *interrupt_handler;
    JSWriteFunc *write_func; /* for the various dump functions */
    void *opaque;
    JSValue *class_obj; /* same as class_proto + class_count */
    JSStringPosCacheEntry string_pos_cache[JS_STRING_POS_CACHE_SIZE];
                                           
    /* must only contain JSValue from this point (see JS_GC()) */
    JSValue unique_strings; /* JSValueArray of sorted strings or JS_NULL */
    
    JSValue current_exception; /* currently pending exception, must
                                  come after unique_strings */
#ifdef DEBUG_GC
    JSValue dummy_block; /* dummy memory block near the start of the memory */
#endif
    JSValue empty_props; /* empty prop list, for objects with no properties */
    JSValue global_obj;
    JSValue minus_zero; /* minus zero float64 value */
    JSValue class_proto[]; /* prototype for each class (class_count
                              element, then class_count elements for
                              class_obj */
};

typedef enum {
    JS_VARREF_KIND_ARG, /* var_idx is an argument of the parent function */
    JS_VARREF_KIND_VAR, /* var_idx is a local variable of the parent function */
    JS_VARREF_KIND_VAR_REF, /* var_idx is a var ref of the parent function */
    JS_VARREF_KIND_GLOBAL, /* to debug */
} JSVarRefKindEnum;

typedef struct JSObject JSObject;

typedef struct {
    /* string, short integer or JS_UNINITIALIZED if no property. If
       the last property is uninitialized, hash_next = 2 *
       first_free. */
    JSValue key;
    /* JS_PROP_GETSET: JSValueArray of two elements
       JS_PROP_VARREF: JSVarRef */
    JSValue value;
    /* XXX: when JSW = 8, could use 32 bits for hash_next (faster) */
    uint32_t hash_next : 30;  /* low bit at zero */
    uint32_t prop_type : 2;
} JSProperty;

typedef struct {
    JSValue func_bytecode; /* JSFunctionBytecode */
    JSValue var_refs[]; /* JSValueArray */
} JSClosureData;

typedef struct {
    uint32_t idx;
    JSValue params; /* optional associated parameters */
} JSCFunctionData;
    
typedef struct {
    JSValue tab; /* JS_NULL or JSValueArray */
    uint32_t len; /* maximum value: 2^30-1 */
} JSArrayData;

typedef struct {
    JSValue message; /* string or JS_NULL */
    JSValue stack; /* string or JS_NULL */
} JSErrorData;
    
typedef struct {
    JSValue byte_buffer; /* JSByteBuffer */
} JSArrayBuffer;

typedef struct {
    JSValue buffer; /* corresponding array buffer */
    uint32_t len; /* in elements */
    uint32_t offset; /* in elements */
} JSTypedArray;

typedef struct {
    JSValue source;
    JSValue byte_code;
    int last_index;
} JSRegExp;

typedef struct
#ifndef JS_PTR64
__attribute__((packed)) /* unaligned 64 bit access in 32-bit mode */
#endif
{
    double dval;
} JSDate;

typedef struct {
    void *opaque;
} JSObjectUserData;

struct JSObject {
    JS_MB_HEADER;
    JSWord class_id: 8;
    JSWord extra_size: JS_MB_PAD(JS_MTAG_BITS + 8);  /* object additional size, in JSValue */

    JSValue proto; /* JSObject or JS_NULL */
    /* JSValueArray. structure:
       prop_count (number of properties excluding deleted ones)
       hash_mask (= hash_size - 1)
       hash_table[hash_size] (0 = end of list or offset in array)
       JSProperty props[]
    */
    JSValue props;
    /* number of additional fields depends on the object */
    union {
        JSClosureData closure;
        JSCFunctionData cfunc;
        JSArrayData array;
        JSErrorData error;
        JSArrayBuffer array_buffer;
        JSTypedArray typed_array;
        JSRegExp regexp;
        JSDate date;
        JSObjectUserData user;
    } u;
};

typedef struct JSFunctionBytecode {
    JS_MB_HEADER;
    JSWord has_arguments : 1; /* only used during parsing */
    JSWord has_local_func_name : 1; /* only used during parsing */
    JSWord has_column : 1; /* column debug info is present */
    /* during parse: variable index + 1 of hoisted function, 0 otherwise */
    JSWord arg_count : 16; 
    JSWord dummy: JS_MB_PAD(JS_MTAG_BITS + 3 + 16);

    JSValue func_name; /* JS_NULL if anonymous function */
    JSValue byte_code; /* JS_NULL if the function is not parsed yet */
    JSValue cpool; /* constant pool */
    JSValue vars; /* only for debug */
    JSValue ext_vars; /* records of (var_name, var_kind (2 bits) var_idx (16 bits)) */
    uint16_t stack_size; /* maximum stack size */
    uint16_t ext_vars_len; /* XXX: only used during parsing */
    JSValue filename; /* filename in which the function is defined */
    JSValue pc2line; /* JSByteArray or JS_NULL if not initialized */
    uint32_t source_pos; /* only used during parsing (XXX: shrink) */
} JSFunctionBytecode;

JSValue js_resize_value_array(JSContext *ctx, JSValue val, int new_size);
int get_mblock_size(const void *ptr); /* body in ae/gc_size.ae */
int mtag_has_references(int mtag); /* body in ae/gc_size.ae */
JSValue JS_NewObjectProtoClass(JSContext *ctx, JSValue proto, int class_id, int extra_size);
static void js_shrink_byte_array(JSContext *ctx, JSValue *pval, int new_size);
void build_backtrace(JSContext *ctx, JSValue error_obj,
                            const char *filename, int line_num, int col_num, int skip_level); /* ae/build_backtrace.ae */
JSValue JS_ToPropertyKey(JSContext *ctx, JSValue val); /* un-static for ae */
JSByteArray *js_alloc_byte_array(JSContext *ctx, int size);
JSValue js_new_c_function_proto(JSContext *ctx, int func_idx, JSValue proto, BOOL has_params,
                                       JSValue params);
int JS_ToUint8Clamp(JSContext *ctx, int *pres, JSValue val);
JSValue js_set_prototype_internal(JSContext *ctx, JSValue obj, JSValue proto);
static JSValue js_resize_byte_array(JSContext *ctx, JSValue val, int new_size);
JSValueArray *js_alloc_props(JSContext *ctx, int n);

typedef enum OPCodeFormat {
#define FMT(f) OP_FMT_ ## f,
#define DEF(id, size, n_pop, n_push, f)
#include "mquickjs_opcode.h"
#undef DEF
#undef FMT
} OPCodeFormat;

typedef enum OPCodeEnum {
#define FMT(f)
#define DEF(id, size, n_pop, n_push, f) OP_ ## id,
#define def(id, size, n_pop, n_push, f)
#include "mquickjs_opcode.h"
#undef def
#undef DEF
#undef FMT
    OP_COUNT,
} OPCodeEnum;

typedef struct {
#ifdef DUMP_BYTECODE
    const char *name;
#endif
    uint8_t size; /* in bytes */
    /* the opcodes remove n_pop items from the top of the stack, then
       pushes n_pusch items */
    uint8_t n_pop;
    uint8_t n_push;
    uint8_t fmt;
} JSOpCode;

static __maybe_unused const JSOpCode opcode_info[OP_COUNT] = {
#define FMT(f)
#ifdef DUMP_BYTECODE
#define DEF(id, size, n_pop, n_push, f) { #id, size, n_pop, n_push, OP_FMT_ ## f },
#else
#define DEF(id, size, n_pop, n_push, f) { size, n_pop, n_push, OP_FMT_ ## f },
#endif
#include "mquickjs_opcode.h"
#undef DEF
#undef FMT
};

/* data accessor so the Aether codegen passes can read the static-const
   opcode_info[] table (size, n_pop, n_push, fmt are bytes 0..3). */
const void *get_opcode_info_table(void) { return opcode_info; }
int get_op_count(void) { return OP_COUNT; }

#include "mquickjs_atom.h"

JSValue *JS_PushGCRef(JSContext *ctx, JSGCRef *ref); /* ae/jscontext.ae */

JSValue JS_PopGCRef(JSContext *ctx, JSGCRef *ref); /* ae/jscontext.ae */

JSValue *JS_AddGCRef(JSContext *ctx, JSGCRef *ref); /* ae/add_gc_ref.ae */

void JS_DeleteGCRef(JSContext *ctx, JSGCRef *ref); /* ae/gcref.ae */

#undef JS_PUSH_VALUE
#undef JS_POP_VALUE

#define JS_PUSH_VALUE(ctx, v) do {               \
        v ## _ref.prev = ctx->top_gc_ref;       \
        ctx->top_gc_ref = &v ## _ref;            \
        v ## _ref.val = v;                     \
    } while (0)
          
#define JS_POP_VALUE(ctx, v) do {                     \
          v = v ## _ref.val;                        \
          ctx->top_gc_ref = v ## _ref.prev;         \
      } while (0)

JSValue js_get_atom(JSContext *ctx, int a); /* ae/jscontext.ae */

static force_inline JSValue JS_NewTailCall(int val)
{
    return JS_VALUE_MAKE_SPECIAL(JS_TAG_EXCEPTION, JS_EX_CALL + val);
}

static inline JS_BOOL JS_IsExceptionOrTailCall(JSValue v)
{
    return JS_VALUE_GET_SPECIAL_TAG(v) == JS_TAG_EXCEPTION;
}

int js_get_mtag(void *ptr); /* ae/jsutil2.ae */

int check_free_mem(JSContext *ctx, JSValue *stack_bottom, uint32_t size); /* ae/check_free_mem.ae */

/* check that 'len' values can be pushed on the stack. Return 0 if OK,
   -1 if not enough space. May trigger a GC(). */
int JS_StackCheck(JSContext *ctx, uint32_t len); /* ae/stack_ctor.ae */

void *js_malloc(JSContext *ctx, uint32_t size, int mtag); /* ae/alloc.ae */

void *js_mallocz(JSContext *ctx, uint32_t size, int mtag); /* ae/alloc.ae */

/* currently only free the last element */
void js_free(JSContext *ctx, void *ptr); /* ae/alloc.ae */

/* 'size' is in bytes and must be multiple of JSW and > 0 */
void set_free_block(void *ptr, uint32_t size); /* ae/mblock.ae */

/* 'ptr' must be != NULL. new_size must be less or equal to the
   current block size. */
void *js_shrink(JSContext *ctx, void *ptr, uint32_t new_size); /* ae/alloc.ae */

JSValue JS_Throw(JSContext *ctx, JSValue obj); /* ae/jscontext.ae */

/* return the byte length. 'buf' must contain UTF8_CHAR_LEN_MAX + 1 bytes */
int get_short_string(uint8_t *buf, JSValue val); /* ae/mblock.ae */

/* printf utility — the format interpreter (js_vprintf) and its variadic
   entry points are ported to Aether; these declarations keep the remaining
   C call-sites and the JS_Throw* macros in mquickjs.h resolving. */
void pad(JSWriteFunc *write_func, void *opaque, char c, int width, int len); /* ae/printf_family.ae */
void js_vprintf(JSWriteFunc *write_func, void *opaque, const char *fmt, va_list ap); /* ae/js_vprintf.ae */
void __attribute__((format(printf, 2, 3))) js_printf(JSContext *ctx, const char *fmt, ...); /* ae/printf_family.ae */
void js_putchar(JSContext *ctx, uint8_t c); /* ae/printf_family.ae */
void snprintf_write_func(void *opaque, const void *buf, size_t buf_len); /* ae/printf_family.ae */
int js_vsnprintf(char *buf, size_t buf_size, const char *fmt, va_list ap); /* ae/printf_family.ae */
int __attribute__((format(printf, 3, 4))) js_snprintf(char *buf, size_t buf_size, const char *fmt, ...); /* ae/printf_family.ae */
JSValue __attribute__((format(printf, 3, 4))) JS_ThrowError(JSContext *ctx, JSObjectClassEnum error_num, const char *fmt, ...); /* ae/printf_family.ae */

JSValue JS_ThrowOutOfMemory(JSContext *ctx); /* ae/misc_helpers.ae */

#define JS_SHORTINT_MIN (-(1 << 30))
#define JS_SHORTINT_MAX ((1 << 30) - 1)

#ifdef JS_USE_SHORT_FLOAT

#define JS_FLOAT64_VALUE_EXP_MIN (1023 - 127)
#define JS_FLOAT64_VALUE_ADDEND ((uint64_t)(JS_FLOAT64_VALUE_EXP_MIN - (JS_TAG_SHORT_FLOAT << 8)) << 52)

/* 1 <= n <= 63 */
static inline uint64_t rotl64(uint64_t a, int n)
{
    return (a << n) | (a >> (64 - n));
}

double js_get_short_float(JSValue v); /* ae/jsbool.ae */

JSValue js_to_short_float(double d); /* ae/jsbool.ae */

#endif /* JS_USE_SHORT_FLOAT */

JSValue js_alloc_float64(JSContext *ctx, double d); /* ae/num_new.ae */

/* create a new float64 value which is known not to be a short integer */

static inline JSValue JS_NewShortInt(int32_t val)
{
    return JS_TAG_INT + (val << 1);
}

JSValue JS_NewFloat64(JSContext *ctx, double d); /* ae/num_new.ae */


JSValue JS_NewInt64(JSContext *ctx, int64_t val); /* ae/num_new.ae */

JSValue JS_NewInt32(JSContext *ctx, int32_t val); /* ae/num_new.ae */

JSValue JS_NewUint32(JSContext *ctx, uint32_t val); /* ae/num_new.ae */

int JS_IsPrimitive(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

/* Note: short functions are not considered as objects by this function */
int JS_IsObject(JSContext *ctx, JSValue val); /* ae/builtins_typedarray.ae */

/* return -1 if not an object */
int JS_GetClassID(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

void JS_SetOpaque(JSContext *ctx, JSValue val, void *opaque); /* ae/object_opaque.ae */

void *JS_GetOpaque(JSContext *ctx, JSValue val); /* ae/object_opaque.ae */

JSObject *js_get_object_class(JSContext *ctx, JSValue val, int class_id); /* ae/builtins_typedarray.ae */

int JS_IsFunction(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

int JS_IsFunctionObject(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

int JS_IsError(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

static force_inline BOOL JS_IsIntOrShortFloat(JSValue val)
{
#ifdef JS_USE_SHORT_FLOAT
    return JS_IsInt(val) || JS_IsShortFloat(val);
#else
    return JS_IsInt(val);
#endif
}

int JS_IsNumber(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

int JS_IsString(JSContext *ctx, JSValue val); /* ae/type_predicates.ae */

JSString *js_alloc_string(JSContext *ctx, uint32_t buf_len); /* ae/alloc_string.ae */

/* 0 <= c <= 0x10ffff */
static inline JSValue JS_NewStringChar(uint32_t c)
{
    return JS_VALUE_MAKE_SPECIAL(JS_TAG_STRING_CHAR, c);
}

static force_inline int utf8_char_len(int c)
{
    int l;
    if (c < 0x80) {
        l = 1;
    } else if (c < 0xc0) {
        l = 1;
    } else if (c < 0xe0) {
        l = 2;
    } else if (c < 0xf0) {
        l = 3;
    } else if (c < 0xf8) {
        l = 4;
    } else {
        l = 1;
    }
    return l;
}

int is_ascii_string(const char *buf, size_t len); /* ae/jshelpers.ae */

JSString *get_string_ptr(JSContext *ctx, JSStringCharBuf *buf,
                               JSValue val); /* ae/get_string_ptr.ae */

JSValue js_sub_string_utf8(JSContext *ctx, JSValue val, uint32_t start0, uint32_t end0); /* ae/sub_string_utf8.ae */

/* Warning: the string must be a valid WTF-8 string (= UTF-8 +
   unpaired surrogates). */
JSValue JS_NewStringLen(JSContext *ctx, const char *buf, size_t len); /* ae/new_string_len.ae */

/* Warning: the string must be a valid UTF-8 string. */
JSValue JS_NewString(JSContext *ctx, const char *buf); /* ae/string_misc.ae */

/* the byte array must be zero terminated. */
JSValue js_byte_array_to_string(JSContext *ctx, JSValue val, int len, BOOL is_ascii); /* ae/byte_array_to_string.ae */

/* in bytes */
int js_string_byte_len(JSContext *ctx, JSValue val); /* ae/string_byte_len.ae */
    
/* assuming that utf8_next() returns 4, validate the corresponding UTF-8 sequence */
int is_valid_len4_utf8(const uint8_t *buf); /* ae/jsutil2.ae */

/* an UTF-8 position is the byte position multiplied by 2. One is
   added when the corresponding UTF-16 character represents the right
   surrogate if the code is >= 0x10000.
*/
uint32_t js_string_convert_pos(JSContext *ctx, JSValue val, uint32_t pos, StringPosTypeEnum pos_type); /* ae/string_convert_pos.ae */

uint32_t js_string_utf16_to_utf8_pos(JSContext *ctx, JSValue val, uint32_t utf16_pos); /* ae/string_pos.ae */

uint32_t js_string_utf8_to_utf16_pos(JSContext *ctx, JSValue val, uint32_t utf8_pos); /* ae/string_pos.ae */

/* Testing the third byte is not needed as the UTF-8 encoding must be
   correct */
int is_utf8_left_surrogate(const uint8_t *p); /* ae/jsutil2.ae */

int is_utf8_right_surrogate(const uint8_t *p); /* ae/jsutil2.ae */

typedef struct {
    JSGCRef buffer_ref; /* string, JSByteBuffer or JS_EXCEPTION */
    int len; /* current string length (in bytes) */
    BOOL is_ascii;
} StringBuffer;

/* return 0 if OK, -1 in case of exception (exception possible if len > 0) */
int string_buffer_push(JSContext *ctx, StringBuffer *s, int len); /* ae/string_buffer_push.ae */

/* val2 must be a string. Return 0 if OK, -1 in case of exception */
int string_buffer_concat_str(JSContext *ctx, StringBuffer *s, JSValue val2); /* ae/sb_concat_str.ae */

/* 'str' must be a string */
int string_buffer_concat_utf8(JSContext *ctx, StringBuffer *s, JSValue str,
                                     uint32_t start, uint32_t end); /* ae/sb_concat_utf.ae */

int string_buffer_concat_utf16(JSContext *ctx, StringBuffer *s, JSValue str,
                                      uint32_t start, uint32_t end); /* ae/sb_concat_utf.ae */

int string_buffer_concat(JSContext *ctx, StringBuffer *s, JSValue val2); /* ae/string_buffer_ops.ae */

/* XXX: could optimize */
int string_buffer_putc(JSContext *ctx, StringBuffer *s, int c); /* ae/string_buffer_putpop.ae */

int string_buffer_puts(JSContext *ctx, StringBuffer *s, const char *str); /* ae/string_buffer_ops.ae */

JSValue string_buffer_pop(JSContext *ctx, StringBuffer *s); /* ae/string_buffer_putpop.ae */

/* val1 and val2 must be strings or exception */
JSValue JS_ConcatString(JSContext *ctx, JSValue val1, JSValue val2); /* ae/concat_string.ae */

int js_string_eq(JSContext *ctx, JSValue val1, JSValue val2); /* ae/string_eq.ae */

/* Return the unicode character containing the byte at position
   'i'. Return -1 in case of error. */
int string_get_cp(const uint8_t *p); /* ae/jsutil2.ae */

int js_string_compare(JSContext *ctx, JSValue val1, JSValue val2); /* ae/string_compare.ae */

/* return the string length in UTF16 characters. 'val' must be a
   string char or a string */
int js_string_len(JSContext *ctx, JSValue val); /* ae/string_misc.ae */

/* return the UTF-16 code or the unicode character at a given UTF-8
   position or -1 if outside the string */
int string_getcp(JSContext *ctx, JSValue str, uint32_t utf16_pos, BOOL is_codepoint); /* ae/string_getcp.ae */

int string_getc(JSContext *ctx, JSValue str, uint32_t utf16_pos); /* ae/string_index.ae */

/* precondition: 0 <= start <= end <= string length */
JSValue js_sub_string(JSContext *ctx, JSValue val, int start, int end); /* ae/builtins_str2.ae */

static inline int is_num(int c)
{
    return c >= '0' && c <= '9';
}

/* return TRUE if the property 'val' represents a numeric property. -1
   is returned in case of exception. 'val' must be a string.  It is
   assumed that NaN and infinities have already been handled. */
int js_is_numeric_string(JSContext *ctx, JSValue val); /* ae/is_numeric_string.ae */

/* return JS_NULL if not found */
JSValue find_atom(JSContext *ctx, int *pidx, const JSValueArray *arr, int len, JSValue val); /* ae/find_atom.ae */

/* if 'val' is not a string, it is returned */
/* XXX: use hash table */
JSValue JS_MakeUniqueString(JSContext *ctx, JSValue val); /* ae/make_unique_string.ae */

int JS_ToBool(JSContext *ctx, JSValue val); /* ae/jsbool.ae */

/* plen can be NULL. No memory allocation is done if 'val' already is
   a string. */
const char *JS_ToCStringLen(JSContext *ctx, size_t *plen, JSValue val,
                            JSCStringBuf *buf); /* ae/to_cstring.ae */

const char *JS_ToCString(JSContext *ctx, JSValue val, JSCStringBuf *buf); /* ae/to_cstring.ae */

int JS_HasException(JSContext *ctx); /* ae/exception_accessors.ae */

JSValue JS_GetException(JSContext *ctx); /* ae/exception_accessors.ae */

JSValue JS_ToStringCheckObject(JSContext *ctx, JSValue val); /* ae/to_string_props.ae */

JSValue JS_ThrowTypeErrorNotAnObject(JSContext *ctx); /* ae/ctx_accessors.ae */

/* 'val' must be a string. return TRUE if the string represents a
   short integer */
BOOL is_num_string(JSContext *ctx, int32_t *pval, JSValue val); /* ae/is_num_string.ae */

/* return TRUE if the property 'val' represent a numeric property. It
   is assumed that the shortint case has been tested before */
int JS_IsNumericProperty(JSContext *ctx, JSValue val); /* ae/exception_accessors.ae */

JSValueArray *js_alloc_value_array(JSContext *ctx, int init_base, int new_size); /* ae/value_array.ae */

/* val can be JS_NULL (zero size). 'prop_base' is non zero only when
 * resizing the property arrays so that the property array has a size
 * which is a multiple of 3 */
JSValue js_resize_value_array2(JSContext *ctx, JSValue val, int new_size, int prop_base); /* ae/resize_value_array.ae */

JSValue js_resize_value_array(JSContext *ctx, JSValue val, int new_size); /* ae/array_shrink.ae */

/* no allocation is done */
void js_shrink_value_array(JSContext *ctx, JSValue *pval, int new_size); /* ae/array_shrink.ae */

JSByteArray *js_alloc_byte_array(JSContext *ctx, int size); /* ae/byte_array.ae */

JSValue js_resize_byte_array(JSContext *ctx, JSValue val, int new_size); /* ae/resize_byte_array.ae */

void js_shrink_byte_array(JSContext *ctx, JSValue *pval, int new_size); /* ae/array_shrink.ae */

/* extra_size is in bytes */
JSObject *JS_NewObjectProtoClass1(JSContext *ctx, JSValue proto,
                                         int class_id, int extra_size); /* ae/object_proto_class1.ae */

JSValue JS_NewObjectProtoClass(JSContext *ctx, JSValue proto, int class_id, int extra_size); /* ae/object_new.ae */

JSValue JS_NewObjectClass(JSContext *ctx, int class_id, int extra_size); /* ae/object_new.ae */

JSValue JS_NewObjectClassUser(JSContext *ctx, int class_id); /* ae/object_new.ae */

JSValue JS_NewObject(JSContext *ctx); /* ae/object_new.ae */

/* same as JS_NewObject() but preallocate for 'n' properties */
JSValue JS_NewObjectPrealloc(JSContext *ctx, int n); /* ae/object_prealloc.ae */

JSValue JS_NewArray(JSContext *ctx, int initial_len); /* ae/new_array.ae */

static inline uint32_t hash_prop(JSValue prop)
{
    return (prop / JSW) ^ (prop % JSW); /* XXX: improve */
}

/* return NULL if not found */
JSProperty *find_own_property_inlined(JSContext *ctx,
                                                          JSObject *p, JSValue prop); /* ae/find_own_prop_inlined.ae */

JSProperty *find_own_property(JSContext *ctx, JSObject *p, JSValue prop); /* ae/float_prop.ae */

JSValue get_special_prop(JSContext *ctx, JSValue val); /* ae/to_string_props.ae */

/* return the value or:
   - exception 
   - tail call : returned in case of getter and handle_getset =
   true. The function is put on the stack
*/
JSValue JS_GetPropertyInternal(JSContext *ctx, JSValue obj, JSValue prop, BOOL allow_tail_call); /* ae/get_property_internal.ae */

JSValue JS_GetProperty(JSContext *ctx, JSValue obj, JSValue prop); /* ae/object_new.ae */

JSValue JS_GetPropertyStr(JSContext *ctx, JSValue this_obj, const char *str); /* ae/prop_str.ae */

JSValue JS_GetPropertyUint32(JSContext *ctx, JSValue obj, uint32_t idx); /* ae/prop_wrappers.ae */

int JS_HasProperty(JSContext *ctx, JSValue obj, JSValue prop); /* ae/has_property.ae */

int get_prop_hash_size_log2(int prop_count); /* ae/jsutil2.ae */

/* allocate 'n' properties, assuming n >= 1 */
JSValueArray *js_alloc_props(JSContext *ctx, int n); /* ae/alloc_props.ae */

void js_rehash_props(JSContext *ctx, JSObject *p, BOOL gc_rehash); /* ae/rehash_props.ae */

/* Compact the properties. No memory allocation is done */
void js_compact_props(JSContext *ctx, JSObject *p); /* ae/compact_props.ae */

/* if the existing properties are in ROM, copy them to RAM. Return non zero if error */
int js_update_props(JSContext *ctx, JSValue obj); /* ae/update_props.ae */

/* compute 'first_free' in a property list */
int get_first_free(JSValueArray *arr); /* ae/mblock.ae */

/* It is assumed that the property does not already exists. */
JSProperty *js_create_property(JSContext *ctx, JSValue obj, JSValue prop); /* ae/create_property.ae */

/* don't do property lookup if not present */
#define JS_DEF_PROP_LOOKUP  (1 << 0)
/* return the raw property value */
#define JS_DEF_PROP_RET_VAL (1 << 1)
#define JS_DEF_PROP_HAS_VALUE (1 << 2)
#define JS_DEF_PROP_HAS_GET   (1 << 3)
#define JS_DEF_PROP_HAS_SET   (1 << 4)

/* XXX: handle arrays and typed arrays */
JSValue JS_DefinePropertyInternal(JSContext *ctx, JSValue obj, JSValue prop, JSValue val, JSValue setter, int flags); /* ae/define_property_internal.ae */

JSValue JS_DefinePropertyValue(JSContext *ctx, JSValue obj, JSValue prop, JSValue val); /* ae/prop_wrappers.ae */

JSValue JS_DefinePropertyGetSet(JSContext *ctx, JSValue obj, JSValue prop, JSValue getter, JSValue setter, int flags); /* ae/prop_wrappers.ae */

/* return a JSVarRef or an exception. */
JSValue add_global_var(JSContext *ctx, JSValue prop, BOOL define_flag); /* ae/add_global_var.ae */

/* return JS_UNDEFINED in the normal case. Otherwise:
   - exception 
   - tail call : returned in case of getter and handle_getset =
   true. The function is put on the stack
*/
JSValue JS_SetPropertyInternal(JSContext *ctx, JSValue this_obj, JSValue prop, JSValue val, BOOL allow_tail_call); /* ae/set_property_internal.ae */

JSValue JS_SetPropertyStr(JSContext *ctx, JSValue this_obj, const char *str, JSValue val); /* ae/prop_str.ae */

JSValue JS_SetPropertyUint32(JSContext *ctx, JSValue this_obj, uint32_t idx, JSValue val); /* ae/prop_wrappers.ae */

/* return JS_FALSE, JS_TRUE or JS_EXCEPTION. Return false only if the
   property is not configurable which is never the case here. */
JSValue JS_DeleteProperty(JSContext *ctx, JSValue this_obj, JSValue prop); /* ae/delete_property.ae */

JSValue stdlib_init_class(JSContext *ctx, const JSROMClass *class_def); /* ae/stdlib_init_class.ae */

void stdlib_init(JSContext *ctx, const JSValueArray *arr); /* ae/stdlib_init.ae */

void dummy_write_func(void *opaque, const void *buf, size_t buf_len); /* ae/new_context.ae */

/* if prepare_compilation is true, the context will be used to compile
   to a binary file. It is not expected to be used in the embedded
   version */
JSContext *JS_NewContext2(void *mem_start, size_t mem_size, const JSSTDLibraryDef *stdlib_def, BOOL prepare_compilation); /* ae/new_context.ae */

JSContext *JS_NewContext(void *mem_start, size_t mem_size, const JSSTDLibraryDef *stdlib_def); /* ae/new_context.ae */

void JS_FreeContext(JSContext *ctx); /* ae/free_context.ae */

void JS_SetContextOpaque(JSContext *ctx, void *opaque); /* ae/jscontext.ae */

void *JS_GetContextOpaque(JSContext *ctx); /* ae/jscontext.ae */

void JS_SetInterruptHandler(JSContext *ctx, JSInterruptHandler *interrupt_handler); /* ae/object_opaque.ae */

void JS_SetLogFunc(JSContext *ctx, JSWriteFunc *write_func); /* ae/ctx_accessors.ae */

void JS_SetRandomSeed(JSContext *ctx, uint64_t seed); /* ae/ctx_accessors.ae */

JSValue JS_GetGlobalObject(JSContext *ctx); /* ae/ctx_accessors.ae */

JSValue get_var_ref(JSContext *ctx, JSValue *pfirst_var_ref, JSValue *pval); /* ae/get_var_ref.ae */

#define FRAME_OFFSET_ARG0       4
#define FRAME_OFFSET_FUNC_OBJ   3
#define FRAME_OFFSET_THIS_OBJ   2
#define FRAME_OFFSET_CALL_FLAGS 1
#define FRAME_OFFSET_SAVED_FP   0
#define FRAME_OFFSET_CUR_PC     (-1) /* current pc_offset */
#define FRAME_OFFSET_FIRST_VARREF (-2)
#define FRAME_OFFSET_VAR0      (-3)

/* stack layout:
   
   padded_args (padded_argc - argc)
   args (argc)
   func_obj                   fp[3]
   this_obj                   fp[2]
   call_flags     (int)       fp[1]
   saved_fp (int)             fp[0]
   cur_pc   (int)             fp[-1]
   first_var_ref (val)        fp[-2]
   vars (var_count)
   temp stack          (pointed by sp)
*/

#define SP_TO_VALUE(ctx, fp) JS_NewShortInt((uint8_t *)(fp) - (uint8_t *)ctx)
#define VALUE_TO_SP(ctx, val) (void *)((uint8_t *)ctx + JS_VALUE_GET_INT(val))

/* buf_end points to the end of the buffer (after the final '\0') */
void __attribute__((format(printf, 3, 4))) cprintf(char **pp, char *buf_end, const char *fmt, ...); /* ae/printf_family.ae */

JSValue reloc_c_func_name(JSContext *ctx, JSValue val); /* ae/stack_ctor.ae */

/* no memory allocation is done */
/* XXX: handle bound functions */
JSValue js_function_get_length_name1(JSContext *ctx, JSValue *this_val, int is_name, JSFunctionBytecode **pb); /* ae/function_length_name.ae */

/* bitstream + pc2line decoders: bodies ported to ae/pc2line.ae */
uint32_t get_bit(const uint8_t *buf, uint32_t index);
uint32_t get_bits_slow(const uint8_t *buf, uint32_t index, int n);
uint32_t get_bits(const uint8_t *buf, uint32_t buf_len, uint32_t index, int n);
uint32_t get_ugolomb(const uint8_t *buf, uint32_t buf_len, uint32_t *pindex);
int32_t get_sgolomb(const uint8_t *buf, uint32_t buf_len, uint32_t *pindex);
int get_pc2line_hoisted_code_len(const uint8_t *buf, size_t buf_len);
void get_pc2line(int *pline_num, int *pcol_num, const uint8_t *buf,
                 uint32_t buf_len, uint32_t *pindex, BOOL has_column);

/* return 0 if line/col number info */
int find_line_col(int *pcol_num, JSFunctionBytecode *b, uint32_t pc); /* ae/find_line_col.ae */

const char *get_func_name(JSContext *ctx, JSValue func_obj,
                          JSCStringBuf *str_buf, JSFunctionBytecode **pb); /* ae/build_backtrace.ae */

/* build_backtrace body is in ae/build_backtrace.ae (forward-declared above). */

#define HINT_STRING  0
#define HINT_NUMBER  1
#define HINT_NONE    HINT_NUMBER

JSValue JS_ToPrimitive(JSContext *ctx, JSValue val, int hint); /* ae/to_primitive.ae */

/* return a string or an exception */
JSValue js_dtoa2(JSContext *ctx, double d, int radix, int n_digits, int flags); /* ae/js_dtoa2.ae */
    
JSValue JS_ToString(JSContext *ctx, JSValue val); /* ae/to_string.ae */

/* return either a unique string or an integer. Strings representing
   a short integer are converted to short integer */
JSValue JS_ToPropertyKey(JSContext *ctx, JSValue val); /* ae/to_string_props.ae */

int skip_spaces(const char *p1); /* ae/jshelpers.ae */

/* JS_ToString() specific behaviors */
#define JS_ATOD_TOSTRING (1 << 8)

/* 'val' must be a string */
int js_atod1(JSContext *ctx, double *pres, JSValue val,
                    int radix, int flags); /* ae/js_dtoa2.ae */

/* Note: can fail due to memory allocation even if primitive type */
int JS_ToNumber(JSContext *ctx, double *pres, JSValue val); /* ae/to_number.ae */

int JS_ToInt32Internal(JSContext *ctx, int *pres, JSValue val, BOOL sat_flag); /* ae/to_int32_internal.ae */

int JS_ToInt32(JSContext *ctx, int *pres, JSValue val); /* ae/to_int32.ae */

int JS_ToUint32(JSContext *ctx, uint32_t *pres, JSValue val); /* ae/to_int32.ae */

int JS_ToInt32Sat(JSContext *ctx, int *pres, JSValue val); /* ae/to_int32.ae */

int JS_ToInt32Clamp(JSContext *ctx, int *pres, JSValue val, int min, int max, int min_offset); /* ae/to_int32.ae */

int JS_ToUint8Clamp(JSContext *ctx, int *pres, JSValue val); /* ae/to_uint8_clamp.ae */

int js_get_length32(JSContext *ctx, uint32_t *pres, JSValue obj); /* ae/strict_eq.ae */

JSValue js_add_slow(JSContext *ctx); /* ae/add_slow.ae */

JSValue js_binary_arith_slow(JSContext *ctx, OPCodeEnum op); /* ae/add_slow.ae */

JSValue js_unary_arith_slow(JSContext *ctx, OPCodeEnum op); /* ae/arith_slow.ae */

/* specific case necessary for correct return value semantics */
JSValue js_post_inc_slow(JSContext *ctx, OPCodeEnum op); /* ae/arith_slow.ae */

JSValue js_binary_logic_slow(JSContext *ctx, OPCodeEnum op); /* ae/arith_slow.ae */

JSValue js_not_slow(JSContext *ctx); /* ae/arith_slow.ae */

JSValue js_relational_slow(JSContext *ctx, OPCodeEnum op); /* ae/relational_slow.ae */

int js_strict_eq(JSContext *ctx, JSValue op1, JSValue op2); /* ae/strict_eq.ae */

JSValue js_strict_eq_slow(JSContext *ctx, BOOL is_neq); /* ae/to_string_props.ae */

enum {
    /* special tags to simplify the comparison */
    JS_ETAG_NUMBER = JS_TAG_SPECIAL | (8 << 2),
    JS_ETAG_STRING = JS_TAG_SPECIAL | (9 << 2),
    JS_ETAG_OBJECT = JS_TAG_SPECIAL | (10 << 2),
};

int js_eq_get_type(JSContext *ctx, JSValue val); /* ae/operator_in.ae */

JSValue js_eq_slow(JSContext *ctx, BOOL is_neq); /* ae/operator_in.ae */

JSValue js_operator_in(JSContext *ctx); /* ae/operator_in.ae */

JSValue js_operator_instanceof(JSContext *ctx); /* ae/operator_in.ae */

JSValue js_operator_typeof(JSContext *ctx, JSValue val); /* ae/operator_in.ae */

void js_reverse_val(JSValue *tab, int n); /* ae/jshelpers.ae */
 
JSValue js_closure(JSContext *ctx, JSValue bfunc, JSValue *fp); /* ae/closure.ae */

JSValue js_for_of_start(JSContext *ctx, BOOL is_for_in); /* ae/for_of.ae */

JSValue js_for_of_next(JSContext *ctx); /* ae/for_of.ae */

JSValue js_new_c_function_proto(JSContext *ctx, int func_idx, JSValue proto, BOOL has_params,
                                       JSValue params); /* ae/new_c_function_proto.ae */

JSValue JS_NewCFunctionParams(JSContext *ctx, int func_idx, JSValue params); /* ae/api_entry.ae */

JSValue js_call_constructor_start(JSContext *ctx, JSValue func); /* ae/stack_ctor.ae */

/* The interrupt poll called by the Aether VM (ae/vm.ae). */
JSValue __js_poll_interrupt(JSContext *ctx); /* ae/interrupt_vars.ae */

/* must use JS_StackCheck() before using it */
void JS_PushArg(JSContext *ctx, JSValue val); /* ae/ctx_accessors.ae */

/* Usage:
   if (JS_StackCheck(ctx, n + 2)) ...
   JS_PushArg(ctx, arg[n - 1]);
   ...
   JS_PushArg(ctx, arg[0]);
   JS_PushArg(ctx, func);
   JS_PushArg(ctx, this_obj);
   res = JS_Call(ctx, n);
*/
/* The bytecode interpreter is ported to Aether: ae/vm.ae provides
   js_call_ae, which JS_Call forwards to. */
JSValue js_call_ae(JSContext *ctx, int call_flags);

/* C trampolines so the Aether VM can invoke C-function pointers it only
   holds as integers (Aether cannot cast/call raw function pointers). */
/* The VM's C-function-pointer trampolines (vm_call_cfunc_*, vm_to_number,
   vm_i2d/u2d/l2d) are ported to Aether (ae/vm.ae) using typed fn-ptr
   dispatch; vm_call_interrupt / vm_call_finalizer likewise. */
JSValue js_throw_prop_access_error(JSContext *ctx, int kind, JSValue prop); /* ae/throw_shims.ae */
JSValue js_throw_global_not_ref(JSContext *ctx, JSValue prop); /* ae/throw_shims.ae */
JSValue js_tostring_mtag_str(JSContext *ctx, int mtag); /* ae/throw_shims.ae */




JSValue JS_Call(JSContext *ctx, int call_flags)
{
    return js_call_ae(ctx, call_flags);
}

static inline int is_ident_first(int c)
{
    return (c >= 'a' && c <= 'z') ||
        (c >= 'A' && c <= 'Z') ||
        c == '_' || c == '$';
}

static inline int is_ident_next(int c)
{
    return is_ident_first(c) || is_num(c);
}

/**********************************************************************/
/* dump utilities */

/* The value pretty-printer (JS_PrintValueF and its js_dump_* / dump_string /
   dump_regexp helpers) and the JS_DumpValue* wrappers are ported to Aether
   (ae/print_value.ae). The memory dumper stays C under JS_DUMP. */
void JS_PrintValueF(JSContext *ctx, JSValue val, int flags); /* ae/print_value.ae */
void JS_PrintValue(JSContext *ctx, JSValue val); /* ae/print_value.ae */
void JS_DumpValueF(JSContext *ctx, const char *str, JSValue val, int flags); /* ae/print_value.ae */
void JS_DumpValue(JSContext *ctx, const char *str, JSValue val); /* ae/print_value.ae */

/* JS_DumpMemory and get_mtag_name are ported to Aether (ae/dump_memory.ae). */
void JS_DumpMemory(JSContext *ctx, BOOL is_long); /* ae/dump_memory.ae */
const char *get_mtag_name(unsigned int mtag); /* ae/dump_memory.ae */


/**************************************************/
/* JS parser */

enum {
    TOK_NUMBER = 128,
    TOK_STRING,
    TOK_IDENT,
    TOK_REGEXP,
    /* warning: order matters (see js_parse_assign_expr) */
    TOK_MUL_ASSIGN, 
    TOK_DIV_ASSIGN, 
    TOK_MOD_ASSIGN, 
    TOK_PLUS_ASSIGN, 
    TOK_MINUS_ASSIGN,
    TOK_SHL_ASSIGN,
    TOK_SAR_ASSIGN,
    TOK_SHR_ASSIGN,
    TOK_AND_ASSIGN,
    TOK_XOR_ASSIGN,
    TOK_OR_ASSIGN,
    TOK_POW_ASSIGN,
    TOK_DEC,
    TOK_INC,
    TOK_SHL,
    TOK_SAR,
    TOK_SHR,
    TOK_LT,
    TOK_LTE,
    TOK_GT,
    TOK_GTE,
    TOK_EQ,
    TOK_STRICT_EQ,
    TOK_NEQ,
    TOK_STRICT_NEQ,
    TOK_LAND,
    TOK_LOR,
    TOK_POW,
    TOK_EOF,
    /* keywords */
    TOK_FIRST_KEYWORD,
    TOK_NULL = TOK_FIRST_KEYWORD + JS_ATOM_null,
    TOK_FALSE = TOK_FIRST_KEYWORD + JS_ATOM_false,
    TOK_TRUE = TOK_FIRST_KEYWORD + JS_ATOM_true,
    TOK_IF = TOK_FIRST_KEYWORD + JS_ATOM_if,
    TOK_ELSE = TOK_FIRST_KEYWORD + JS_ATOM_else,
    TOK_RETURN = TOK_FIRST_KEYWORD + JS_ATOM_return,
    TOK_VAR = TOK_FIRST_KEYWORD + JS_ATOM_var,
    TOK_THIS = TOK_FIRST_KEYWORD + JS_ATOM_this,
    TOK_DELETE = TOK_FIRST_KEYWORD + JS_ATOM_delete,
    TOK_VOID = TOK_FIRST_KEYWORD + JS_ATOM_void,
    TOK_TYPEOF = TOK_FIRST_KEYWORD + JS_ATOM_typeof,
    TOK_NEW = TOK_FIRST_KEYWORD + JS_ATOM_new,
    TOK_IN = TOK_FIRST_KEYWORD + JS_ATOM_in,
    TOK_INSTANCEOF = TOK_FIRST_KEYWORD + JS_ATOM_instanceof,
    TOK_DO = TOK_FIRST_KEYWORD + JS_ATOM_do,
    TOK_WHILE = TOK_FIRST_KEYWORD + JS_ATOM_while,
    TOK_FOR = TOK_FIRST_KEYWORD + JS_ATOM_for,
    TOK_BREAK = TOK_FIRST_KEYWORD + JS_ATOM_break,
    TOK_CONTINUE = TOK_FIRST_KEYWORD + JS_ATOM_continue,
    TOK_SWITCH = TOK_FIRST_KEYWORD + JS_ATOM_switch,
    TOK_CASE = TOK_FIRST_KEYWORD + JS_ATOM_case,
    TOK_DEFAULT = TOK_FIRST_KEYWORD + JS_ATOM_default,
    TOK_THROW = TOK_FIRST_KEYWORD + JS_ATOM_throw,
    TOK_TRY = TOK_FIRST_KEYWORD + JS_ATOM_try,
    TOK_CATCH = TOK_FIRST_KEYWORD + JS_ATOM_catch,
    TOK_FINALLY = TOK_FIRST_KEYWORD + JS_ATOM_finally,
    TOK_FUNCTION = TOK_FIRST_KEYWORD + JS_ATOM_function,
    TOK_DEBUGGER = TOK_FIRST_KEYWORD + JS_ATOM_debugger,
    TOK_WITH = TOK_FIRST_KEYWORD + JS_ATOM_with,
    TOK_CLASS = TOK_FIRST_KEYWORD + JS_ATOM_class,
    TOK_CONST = TOK_FIRST_KEYWORD + JS_ATOM_const,
    TOK_ENUM = TOK_FIRST_KEYWORD + JS_ATOM_enum,
    TOK_EXPORT = TOK_FIRST_KEYWORD + JS_ATOM_export,
    TOK_EXTENDS = TOK_FIRST_KEYWORD + JS_ATOM_extends,
    TOK_IMPORT = TOK_FIRST_KEYWORD + JS_ATOM_import,
    TOK_SUPER = TOK_FIRST_KEYWORD + JS_ATOM_super,
    TOK_IMPLEMENTS = TOK_FIRST_KEYWORD + JS_ATOM_implements,
    TOK_INTERFACE = TOK_FIRST_KEYWORD + JS_ATOM_interface,
    TOK_LET = TOK_FIRST_KEYWORD + JS_ATOM_let,
    TOK_PACKAGE = TOK_FIRST_KEYWORD + JS_ATOM_package,
    TOK_PRIVATE = TOK_FIRST_KEYWORD + JS_ATOM_private,
    TOK_PROTECTED = TOK_FIRST_KEYWORD + JS_ATOM_protected,
    TOK_PUBLIC = TOK_FIRST_KEYWORD + JS_ATOM_public,
    TOK_STATIC = TOK_FIRST_KEYWORD + JS_ATOM_static,
    TOK_YIELD = TOK_FIRST_KEYWORD + JS_ATOM_yield,
};

/* this structure is pushed on the JS stack, so all members must be JSValue */
typedef struct BlockEnv {
    JSValue prev; /* JS_NULL or stack index */
    JSValue label_name; /* JS_NULL if none */
    JSValue label_break;
    JSValue label_cont;
    JSValue label_finally;
    JSValue drop_count; /* (int) number of stack elements to drop */
} BlockEnv;

typedef uint32_t JSSourcePos;

typedef struct JSToken {
    int val;
    JSSourcePos source_pos; /* position in source */
    union {
        double d; /* TOK_NUMBER */
        struct {
            uint32_t re_flags; /* regular expression flags */
            uint32_t re_end_pos; /* at the final '/' */
        } regexp;
    } u;
    JSValue value; /* associated value: string for TOK_STRING, TOK_REGEXP;
                      identifier for TOK_IDENT or keyword */
} JSToken;

typedef struct JSParseState {
    JSContext *ctx;
    JSToken token;

    BOOL got_lf : 8; /* true if got line feed before the current token */
    /* global eval: variables are defined as global */
    BOOL is_eval : 8;
    /* if true, return the last value. */
    BOOL has_retval : 8;
    /* if true, implicitly define global variables in an
       assignment. */
    BOOL is_repl : 8;
    BOOL has_column : 8; /* column debug info is present */
    /* TRUE if the expression result has been dropped (see PF_DROP) */
    BOOL dropped_result : 8;
    JSValue source_str; /* source string or JS_NULL */
    JSValue filename_str; /* 'filename' converted to string */
    /* zero terminated source buffer. Automatically updated by the GC
       if source_str is a string */
    const uint8_t *source_buf; 
    uint32_t buf_pos;
    uint32_t buf_len;

    /* current function */
    JSValue cur_func;
    JSValue byte_code;
    uint32_t byte_code_len;
    int last_opcode_pos; /* -1 if no last opcode */
    int last_pc2line_pos; /* pc2line pos for the last opcode */
    JSSourcePos last_pc2line_source_pos;
    
    uint32_t pc2line_bit_len;
    JSSourcePos pc2line_source_pos; /* last generated source pos */
    
    uint16_t cpool_len;
    /* size of the byte code necessary to define the hoisted functions  */
    uint32_t hoisted_code_len;
    
    /* argument + defined local variable count */
    uint16_t local_vars_len;
    
    int eval_ret_idx; /* variable index for the eval return value, -1
                         if no return value */
    JSValue top_break; /* JS_NULL or SP_TO_VALUE(BlockEnv *) */

    /* regexp parsing only */
    uint8_t capture_count;
    uint8_t re_in_js: 1;
    uint8_t multi_line : 1;
    uint8_t dotall : 1;
    uint8_t ignore_case : 1;
    uint8_t is_unicode : 1;

    /* error handling */
    jmp_buf jmp_env;
    char error_msg[64];
} JSParseState;

int js_parse_json_value(JSParseState *s, int state, int dummy_param);
JSValue js_parse_regexp(JSParseState *s, int eval_flags);
size_t js_parse_regexp_flags(int *pre_flags, const uint8_t *buf); /* ae/regexp_flags.ae */
int re_parse_alternative(JSParseState *s, int state, int dummy_param);
int re_parse_disjunction(JSParseState *s, int state, int dummy_param);

#ifdef DUMP_BYTECODE
#endif /* DUMP_BYTECODE */

void next_token(JSParseState *s);


/* return the zero based line and column number in the source. */
int get_line_col(int *pcol_num, const uint8_t *buf, size_t len); /* ae/jshelpers.ae */

void __attribute__((format(printf, 2, 3), noreturn)) js_parse_error(JSParseState *s, const char *fmt, ...); /* ae/parse_errors.ae */
void js_parse_error_mem(JSParseState *s); /* ae/parse_expect.ae */
void js_parse_error_pc1(JSParseState *s, int kind, int a); /* ae/parse_errors.ae */
void js_parse_error_pc3(JSParseState *s, int a, int b, int pc); /* ae/parse_errors.ae */
void js_parse_error_expect_char(JSParseState *s, int c); /* ae/parse_errors.ae */
void js_parse_error_lvalue_delete(JSParseState *s); /* ae/parse_errors.ae */
JSValue js_throw_circular_ref(JSContext *ctx); /* ae/throw_shims.ae */
JSValue js_throw_bytecode_expected(JSContext *ctx); /* ae/throw_shims.ae */
void js_parse_error_re_extraneous(JSParseState *s); /* ae/parse_errors.ae */
void js_parse_error_func_name(JSParseState *s); /* ae/parse_errors.ae */
void js_parse_error_nested_blocks(JSParseState *s); /* ae/parse_errors.ae */

void js_emit_u_escape(JSContext *ctx, StringBuffer *b, int c); /* ae/throw_shims.ae */

void js_parse_error_stack_overflow(JSParseState *s); /* ae/parse_expect.ae */

void js_parse_expect1(JSParseState *s, int ch); /* ae/parse_expect.ae */

void js_parse_expect(JSParseState *s, int ch); /* ae/parse_expect.ae */

void js_parse_expect_semi(JSParseState *s); /* ae/parse_expect.ae */

#define SKIP_HAS_ARGUMENTS     (1 << 0)
#define SKIP_HAS_FUNC_NAME     (1 << 1)
#define SKIP_HAS_SEMI          (1 << 2) /* semicolon found inside the first level */

/* Skip parenthesis or blocks. The current token should be '(', '[' or
   '{'. 'func_name' can be JS_NULL. */
int js_skip_parens(JSParseState *s, JSValue *pfunc_name); /* ae/skip_parens.ae */

/* skip an expression until ')' */
void js_skip_expr(JSParseState *s); /* ae/skip_expr.ae */

typedef struct JSParsePos {
    BOOL got_lf : 8;
    BOOL regexp_allowed : 8;
    uint32_t source_pos;
} JSParsePos;

/* return TRUE if a regexp literal is allowed after this token */
BOOL is_regexp_allowed(int tok); /* ae/is_regexp_allowed.ae */

void js_parse_get_pos(JSParseState *s, JSParsePos *sp); /* ae/parse_leaf.ae */

void js_parse_seek_token(JSParseState *s, const JSParsePos *sp); /* ae/parse_leaf.ae */

/* same as js_skip_parens but go back to the current token */
int js_parse_skip_parens_token(JSParseState *s); /* ae/skip_parens_token.ae */

/* return the escape value or -1 */
int js_parse_escape(const uint8_t *buf, size_t *plen); /* ae/parse_escape.ae */

JSValue js_parse_string(JSParseState *s, uint32_t *ppos, int sep); /* ae/parse_string.ae */

void js_parse_ident(JSParseState *s, JSToken *token, uint32_t *ppos, int c); /* ae/parse_ident.ae */

void js_parse_regexp_token(JSParseState *s, uint32_t *ppos); /* ae/parse_regexp_token.ae */

void next_token(JSParseState *s); /* ae/next_token.ae */

/* test if the current token is a label. XXX: we assume there is no
   space between the identifier and the ':' to avoid having to push
   back a token */
BOOL is_label(JSParseState *s); /* ae/skip_expr.ae */

static inline uint8_t *get_byte_code(JSParseState *s)
{
    JSByteArray *arr;
    arr = JS_VALUE_TO_PTR(s->byte_code);
    return arr->buf;
}

void emit_claim_size(JSParseState *s, int n); /* ae/emit.ae */

void emit_u8(JSParseState *s, uint8_t val); /* ae/emit.ae */

void emit_u16(JSParseState *s, uint16_t val); /* ae/emit.ae */

void emit_u32(JSParseState *s, uint32_t val); /* ae/emit.ae */

/* precondition: 1 <= n <= 25. */
void pc2line_put_bits_short(JSParseState *s, int n, uint32_t bits); /* ae/pc2line_emit.ae */

/* precondition: 1 <= n <= 32 */
void pc2line_put_bits(JSParseState *s, int n, uint32_t bits); /* ae/pc2line_emit.ae */

/* 0 <= v < 2^32-1 */
void put_ugolomb(JSParseState *s, uint32_t v); /* ae/pc2line_emit.ae */

/* v != -2^31 */
void put_sgolomb(JSParseState *s, int32_t v1); /* ae/pc2line_emit.ae */

//#define DUMP_PC2LINE_STATS

#ifdef DUMP_PC2LINE_STATS
static int pc2line_freq[256];
static int pc2line_freq_tot;
#endif

/* return the difference between the line numbers from 'pos1' to
   'pos2'. If the difference is zero, '*pcol_num' contains the
   difference between the column numbers. Otherwise it contains the
   zero based absolute column number.
*/
int get_line_col_delta(int *pcol_num, const uint8_t *buf, int pos1, int pos2); /* ae/jshelpers.ae */

void emit_pc2line(JSParseState *s, JSSourcePos pos); /* ae/emit_pc2line.ae */

#ifdef DUMP_PC2LINE_STATS
void dump_pc2line(void)
{
    int i;
    for(i = 0; i < 256; i++) {
        if (pc2line_freq[i] != 0) {
            printf("%d: %d %0.2f\n",
                   i - 128, pc2line_freq[i],
                   -log2((double)pc2line_freq[i] / pc2line_freq_tot));
        }
    }
}
#endif

/* warning: pc2line info must be associated to each generated opcode */
void emit_op_pos(JSParseState *s, uint8_t op, JSSourcePos source_pos); /* ae/emit.ae */

void emit_op(JSParseState *s, uint8_t op); /* ae/emit.ae */

void emit_op_param(JSParseState *s, uint8_t op, uint32_t param, JSSourcePos source_pos); /* ae/emit_op_param.ae */

/* insert 'n' bytes at position pos */
void emit_insert(JSParseState *s, int pos, int n); /* ae/emit.ae */

int get_prev_opcode(JSParseState *s); /* ae/emit_pc2line.ae */

BOOL js_is_live_code(JSParseState *s); /* ae/parse_leaf.ae */

void remove_last_op(JSParseState *s); /* ae/emit.ae */

void emit_push_short_int(JSParseState *s, int val); /* ae/emit.ae */

void emit_var(JSParseState *s, int opcode, int var_idx, JSSourcePos source_pos); /* ae/emit.ae */


typedef enum {
    JS_PARSE_FUNC_STATEMENT,
    JS_PARSE_FUNC_EXPR,
    JS_PARSE_FUNC_METHOD,
} JSParseFunctionEnum;

void js_parse_function_decl(JSParseState *s,
                                   JSParseFunctionEnum func_type, JSValue func_name);

/* labels are short integers so they can be used as JSValue. -1 is not
   a valid label. */
#define LABEL_RESOLVED_FLAG (1 << 29)
#define LABEL_OFFSET_MASK ((1 << 29) - 1)

#define LABEL_NONE JS_NewShortInt(-1)

int label_is_none(JSValue label); /* ae/jshelpers.ae */

JSValue new_label(JSParseState *s); /* ae/parse_leaf.ae */

void emit_label_pos(JSParseState *s, JSValue *plabel, int pos); /* ae/emit_label.ae */

void emit_label(JSParseState *s, JSValue *plabel); /* ae/emit_label.ae */

void emit_goto(JSParseState *s, int opcode, JSValue *plabel); /* ae/emit_label.ae */

/* return the constant pool index. 'val' is not duplicated. */
int cpool_add(JSParseState *s, JSValue val); /* ae/cpool.ae */

void js_emit_push_const(JSParseState *s, JSValue val); /* ae/emit.ae */

/* return the local variable index or -1 if not found */
int find_func_var(JSContext *ctx, JSValue func, JSValue name); /* ae/interrupt_vars.ae */

int find_var(JSParseState *s, JSValue name); /* ae/define_var.ae */

JSValue get_ext_var_name(JSParseState *s, int var_idx); /* ae/ext_var.ae */

int find_func_ext_var(JSParseState *s, JSValue func, JSValue name); /* ae/ext_var.ae */

/* return the external variable index or -1 if not found */
int find_ext_var(JSParseState *s, JSValue name); /* ae/ext_var.ae */

/* return the external variable index */
int add_func_ext_var(JSParseState *s, JSValue func, JSValue name, int decl); /* ae/ext_var.ae */

/* return the external variable index */
int add_ext_var(JSParseState *s, JSValue name, int decl); /* ae/ext_var.ae */

/* return the local variable index */
int add_var(JSParseState *s, JSValue name); /* ae/add_var.ae */

void get_lvalue(JSParseState *s, int *popcode, int *pvar_idx, JSSourcePos *psource_pos, BOOL keep); /* ae/get_lvalue.ae */

typedef enum {
    PUT_LVALUE_KEEP_TOP,  /* [depth] v -> v */
    PUT_LVALUE_NOKEEP_TOP, /* [depth] v -> */
    PUT_LVALUE_KEEP_SECOND, /* [depth] v0 v -> v0 */
    PUT_LVALUE_NOKEEP_BOTTOM, /* v [depth] -> */
} PutLValueEnum;

void put_lvalue(JSParseState *s, int opcode,
                       int var_idx, JSSourcePos source_pos,
                       PutLValueEnum special); /* ae/put_lvalue.ae */

enum {
    PARSE_PROP_FIELD,
    PARSE_PROP_GET,
    PARSE_PROP_SET,
    PARSE_PROP_METHOD,
};

int js_parse_property_name(JSParseState *s, JSValue *pname); /* ae/parse_property_name.ae */

/* recursion free parser definitions */

#define PF_NO_IN         (1 << 0) /* the 'in' operator is not accepted*/
#define PF_DROP          (1 << 1) /* drop result */
#define PF_ACCEPT_LPAREN (1 << 2) /* js_parse_postfix_expr only */
#define PF_LEVEL_SHIFT 4 /* optional level parameter */
#define PF_LEVEL_MASK  (0xf << PF_LEVEL_SHIFT)

typedef enum {
    PARSE_FUNC_js_parse_expr_comma,
    PARSE_FUNC_js_parse_assign_expr,
    PARSE_FUNC_js_parse_cond_expr,
    PARSE_FUNC_js_parse_logical_and_or,
    PARSE_FUNC_js_parse_expr_binary,
    PARSE_FUNC_js_parse_unary,
    PARSE_FUNC_js_parse_postfix_expr,
    PARSE_FUNC_js_parse_statement,
    PARSE_FUNC_js_parse_block,
    PARSE_FUNC_js_parse_json_value,
    PARSE_FUNC_re_parse_alternative,
    PARSE_FUNC_re_parse_disjunction,
} ParseExprFuncEnum;

typedef int JSParseFunc(JSParseState *s, int state, int param);

#define PARSE_STATE_INIT 0xfe
#define PARSE_STATE_RET  0xff

/* may trigger a gc */
JSValue parse_stack_alloc(JSParseState *s, JSValue val); /* ae/parse_stack_alloc.ae */

/* WARNING: 'val' may be modified after this val if it is a pointer */
void js_parse_push_val(JSParseState *s, JSValue val); /* ae/parse_stack.ae */

/* update the stack bottom when there is a large stack space */
JSValue js_parse_pop_val(JSParseState *s); /* ae/parse_stack.ae */

#define PARSE_PUSH_VAL(s, v) js_parse_push_val(s, v)
#define PARSE_POP_VAL(s, v) v = js_parse_pop_val(s)

#define PARSE_PUSH_INT(s, v) js_parse_push_val(s, JS_NewShortInt(v))
#define PARSE_POP_INT(s, v) v = JS_VALUE_GET_INT(js_parse_pop_val(s))

#define PARSE_START1()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    }

#define PARSE_START2()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    }

#define PARSE_START3()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    case 2: goto parse_state2;\
    }

#define PARSE_START7()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    case 2: goto parse_state2;\
    case 3: goto parse_state3;                  \
    case 4: goto parse_state4;\
    case 5: goto parse_state5;\
    case 6: goto parse_state6;\
    }

#define PARSE_START12()                          \
    switch(state) {\
    case PARSE_STATE_INIT: break;\
    default: abort();\
    case 0: goto parse_state0;\
    case 1: goto parse_state1;\
    case 2: goto parse_state2;\
    case 3: goto parse_state3;                  \
    case 4: goto parse_state4;\
    case 5: goto parse_state5;\
    case 6: goto parse_state6;\
    case 7: goto parse_state7;                  \
    case 8: goto parse_state8;\
    case 9: goto parse_state9;\
    case 10: goto parse_state10;\
    case 11: goto parse_state11;\
    }

/* WARNING: local variables are not preserved across PARSE_CALL(). So
   they must be explicitly saved and restored */
#define PARSE_CALL(s, cur_state, func, param) return (cur_state | (PARSE_FUNC_ ## func << 8) | ((param) << 16)); parse_state ## cur_state : ;

/* preserve var1, ... across the call */
#define PARSE_CALL_SAVE1(s, cur_state, func, param, var1) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE2(s, cur_state, func, param, var1, var2) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE3(s, cur_state, func, param, var1, var2, var3)        \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE4(s, cur_state, func, param, var1, var2, var3, var4)  \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_PUSH_INT(s, var4);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var4);                                     \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE5(s, cur_state, func, param, var1, var2, var3, var4, var5) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_PUSH_INT(s, var4);                                    \
    PARSE_PUSH_INT(s, var5);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var5);                                     \
    PARSE_POP_INT(s, var4);                                     \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

#define PARSE_CALL_SAVE6(s, cur_state, func, param, var1, var2, var3, var4, var5, var6) \
    PARSE_PUSH_INT(s, var1);                                    \
    PARSE_PUSH_INT(s, var2);                                    \
    PARSE_PUSH_INT(s, var3);                                    \
    PARSE_PUSH_INT(s, var4);                                    \
    PARSE_PUSH_INT(s, var5);                                    \
    PARSE_PUSH_INT(s, var6);                                    \
    PARSE_CALL(s, cur_state, func, param);                      \
    PARSE_POP_INT(s, var6);                                     \
    PARSE_POP_INT(s, var5);                                     \
    PARSE_POP_INT(s, var4);                                     \
    PARSE_POP_INT(s, var3);                                     \
    PARSE_POP_INT(s, var2);                                     \
    PARSE_POP_INT(s, var1);

static JSParseFunc *parse_func_table[];

void js_parse_call(JSParseState *s, ParseExprFuncEnum func_idx, int param); /* ae/parse_call.ae */

void js_emit_push_number(JSParseState *s, double d); /* ae/emit.ae */

int js_parse_postfix_expr(JSParseState *s, int state, int parse_flags); /* ae/parse_postfix.ae */

void js_emit_delete(JSParseState *s); /* ae/emit.ae */

int js_parse_unary(JSParseState *s, int state, int parse_flags); /* ae/parse_unary.ae */

int js_parse_expr_binary(JSParseState *s, int state, int parse_flags); /* ae/parse_binary.ae */

int js_parse_logical_and_or(JSParseState *s, int state, int parse_flags); /* ae/parse_assign.ae */
int js_parse_cond_expr(JSParseState *s, int state, int parse_flags); /* ae/parse_assign.ae */
int js_parse_assign_expr(JSParseState *s, int state, int parse_flags); /* ae/parse_assign.ae */
int js_parse_expr_comma(JSParseState *s, int state, int parse_flags); /* ae/parse_assign.ae */

void js_parse_assign_expr2(JSParseState *s, int parse_flags); /* ae/parse_expr_wrap.ae */

void js_parse_expr2(JSParseState *s, int parse_flags); /* ae/parse_expr_wrap.ae */

void js_parse_expr(JSParseState *s); /* ae/parse_expr_wrap.ae */

void js_parse_expr_paren(JSParseState *s); /* ae/parse_expr_wrap.ae */

BlockEnv *push_break_entry(JSParseState *s, JSValue label_name,
                                  JSValue label_break, JSValue label_cont,
                                  int drop_count); /* ae/parse_stack_alloc.ae */

void pop_break_entry(JSParseState *s); /* ae/parse_stack_alloc.ae */

void emit_return(JSParseState *s, BOOL hasval, JSSourcePos source_pos); /* ae/emit_ctrl.ae */

void emit_break(JSParseState *s, JSValue label_name, int is_cont); /* ae/emit_ctrl.ae */

int define_var(JSParseState *s, JSVarRefKindEnum *pvar_kind, JSValue name); /* ae/define_var.ae */

void put_var(JSParseState *s, JSVarRefKindEnum var_kind, int var_idx, JSSourcePos source_pos); /* ae/put_var.ae */

void js_parse_var(JSParseState *s, BOOL in_accepted); /* ae/parse_var.ae */

void set_eval_ret_undefined(JSParseState *s); /* ae/put_var.ae */

int js_parse_block(JSParseState *s, int state, int dummy_param); /* ae/parse_block.ae */

/* The statement parser assumes that the stack contains the result of
   the last statement. Note: if not in eval code, the return value of
   a statement does not matter */
int js_parse_statement(JSParseState *s, int state, int dummy_param); /* ae/parse_statement.ae */

static JSParseFunc *parse_func_table[] = {
    js_parse_expr_comma,
    js_parse_assign_expr,
    js_parse_cond_expr,
    js_parse_logical_and_or,
    js_parse_expr_binary,
    js_parse_unary,
    js_parse_postfix_expr,
    js_parse_statement,
    js_parse_block,
    js_parse_json_value,
    re_parse_alternative,
    re_parse_disjunction,
};

void js_parse_source_element(JSParseState *s); /* ae/parse_program.ae */
    
JSFunctionBytecode *js_alloc_function_bytecode(JSContext *ctx); /* ae/alloc_func_bytecode.ae */

/* the current token must be TOK_FUNCTION for JS_PARSE_FUNC_STATEMENT
   or JS_PARSE_FUNC_EXPR. Otherwise it is '('. */
void js_parse_function_decl(JSParseState *s,
                                   JSParseFunctionEnum func_type, JSValue func_name); /* ae/parse_function_decl.ae */

void define_hoisted_functions(JSParseState *s, BOOL is_eval); /* ae/define_hoisted_functions.ae */

void js_parse_function(JSParseState *s); /* ae/parse_function.ae */

void js_parse_program(JSParseState *s); /* ae/parse_program.ae */

void convert_ext_vars_to_local_vars(JSParseState *s); /* ae/convert_ext_vars.ae */

/* prepare the analysis of the code starting at position 'pos' */
void compute_stack_size_push(JSParseState *s, JSByteArray *arr, uint8_t *explore_tab, uint32_t pos, int stack_len); /* ae/compute_stack_size.ae */

void compute_stack_size(JSParseState *s, JSValue *pfunc); /* ae/compute_stack_size.ae */

void resolve_var_refs(JSParseState *s, JSValue *pfunc, JSValue *pparent_func); /* ae/resolve_var_refs.ae */

void reset_parse_state(JSParseState *s, uint32_t input_pos,
                              JSValue cur_func); /* ae/reset_parse_state.ae */

void js_parse_local_functions(JSParseState *s, JSValue *pfunc); /* ae/parse_local_functions.ae */

/* return the parsed value in s->token.value */
/* XXX: use exact JSON white space definition */
int js_parse_json_value(JSParseState *s, int state, int dummy_param); /* ae/parse_json.ae */

JSValue js_parse_json(JSParseState *s); /* ae/parse_json_driver.ae */

/* source_str must be a string or JS_NULL. (input, input_len) is
   meaningful only if source_str is JS_NULL. */
JSValue JS_Parse2(JSContext *ctx, JSValue source_str,
                         const char *input, size_t input_len,
                         const char *filename, int eval_flags); /* ae/parse2.ae */

/* warning: it is assumed that input[input_len] = '\0' */
JSValue JS_Parse(JSContext *ctx, const char *input, size_t input_len, const char *filename, int eval_flags); /* ae/api_entry.ae */

JSValue JS_Run(JSContext *ctx, JSValue val); /* ae/js_run.ae */

/* warning: it is assumed that input[input_len] = '\0' */
JSValue JS_Eval(JSContext *ctx, const char *input, size_t input_len, const char *filename, int eval_flags); /* ae/api_entry.ae */

/**********************************************************************/
/* garbage collector */

/* return the size in bytes */

/* gc mark pass */

typedef struct {
    JSContext *ctx;
    JSValue *gsp;
    JSValue *gs_bottom;
    JSValue *gs_top;
    BOOL overflow;
} GCMarkState;



/* flush the GC mark stack */


/* return true if the memory block is marked i.e. it won't be freed by the GC */

void gc_mark_all(JSContext *ctx, BOOL keep_atoms); /* ae/gc_mark.ae */

JSValue js_value_from_pval(JSContext *ctx, JSValue *pval); /* ae/ptr_helpers.ae */

void gc_thread_pointer(JSContext *ctx, JSValue *pval); /* ae/gc_thread_pointer.ae */

void gc_update_threaded_pointers(JSContext *ctx, void *ptr, void *new_ptr); /* ae/gc_compact.ae */

void gc_thread_block(JSContext *ctx, void *ptr); /* ae/gc_compact.ae */

/* Heap compaction using Jonkers algorithm */
void gc_compact_heap(JSContext *ctx); /* ae/gc_compact.ae */

void JS_GC2(JSContext *ctx, BOOL keep_atoms); /* ae/js_gc.ae */

void JS_GC(JSContext *ctx); /* ae/api_entry.ae */

/* bytecode saving and loading */

#define JS_BYTECODE_VERSION_32 0x0001
/* bit 15 of bytecode version is a 64-bit indicator */
#define JS_BYTECODE_VERSION (JS_BYTECODE_VERSION_32 | ((JSW & 8) << 12))

void JS_PrepareBytecode(JSContext *ctx,
                        JSBytecodeHeader *hdr,
                        const uint8_t **pdata_buf, uint32_t *pdata_len,
                        JSValue eval_code); /* ae/relocate_bytecode.ae */

/* The 64->32 bytecode cross-compilation cluster is ported to Aether
   (ae/bytecode_64to32.ae). The forward declarations keep mqjs.c (the only
   caller, behind its own #if JSW == 8) resolving. */
#if JSW == 8
int JS_PrepareBytecode64to32(JSContext *ctx, JSBytecodeHeader32 *hdr,
                             const uint8_t **pdata_buf, uint32_t *pdata_len,
                             JSValue eval_code); /* ae/bytecode_64to32.ae */
#endif /* JSW == 8 */

BOOL JS_IsBytecode(const uint8_t *buf, size_t buf_len); /* ae/bc_sort_helpers.ae */

typedef struct {
    JSContext *ctx;
    uintptr_t offset;
    BOOL update_atoms;
} BCRelocState;

void bc_reloc_value(BCRelocState *s, JSValue *pval); /* ae/relocate_bytecode.ae */

int JS_RelocateBytecode2(JSContext *ctx, JSBytecodeHeader *hdr,
                         uint8_t *buf, uint32_t buf_len,
                         uintptr_t new_base_addr, BOOL update_atoms); /* ae/relocate_bytecode.ae */

/* Relocate the bytecode in 'buf' so that it can be executed
   later. Return 0 if OK, != 0 if error */
int JS_RelocateBytecode(JSContext *ctx, uint8_t *buf, uint32_t buf_len); /* ae/reloc_class.ae */

/* Load the precompiled bytecode from 'buf'. 'buf' must be allocated
   as long as the JSContext exists. Use JS_Run() to execute
   it. warning: the bytecode is not checked so it should come from a
   trusted source. */
JSValue JS_LoadBytecode(JSContext *ctx, const uint8_t *buf); /* ae/relocate_bytecode.ae */

/**********************************************************************/
/* runtime */

JSValue js_function_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func2.ae */

JSValue js_function_get_prototype(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func2.ae */

JSValue js_function_set_prototype(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func.ae */

JSValue js_function_get_length_name(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_name); /* ae/builtins_func2.ae */

JSValue js_function_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func2.ae */

JSValue js_function_call(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func.ae */

JSValue js_function_apply(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func.ae */

JSValue js_function_bind(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func2.ae */

/* XXX: handle constructor case */
JSValue js_function_bound(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, JSValue params); /* ae/builtins_func2.ae */

/**********************************************************************/

JSValue js_number_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_ctor.ae */

int js_thisNumberValue(JSContext *ctx, double *pres, JSValue val); /* ae/misc_helpers.ae */

JSValue js_number_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_numfmt.ae */

JSValue js_number_toFixed(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_numfmt.ae */

JSValue js_number_toExponential(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_numfmt.ae */

JSValue js_number_toPrecision(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_numfmt.ae */

JSValue js_number_parseInt(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_number.ae */

JSValue js_number_parseFloat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_number.ae */

/**********************************************************************/

JSValue js_boolean_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_number.ae */

/**********************************************************************/

JSValue js_string_get_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_string.ae */

JSValue js_string_set_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_ctor.ae */

JSValue js_string_slice(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_str2.ae */

JSValue js_string_substring(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_str2.ae */

JSValue js_string_charAt(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_charat.ae */

JSValue js_string_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_strctor.ae */

JSValue js_string_fromCharCode(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_fromCodePoint); /* ae/builtins_strctor.ae */

JSValue js_string_concat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_concat.ae */

JSValue js_string_indexOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int lastIndexOf); /* ae/builtins_indexof.ae */

int js_string_indexof(JSContext *ctx, JSValue str, JSValue needle, int start, int str_len, int needle_len); /* ae/string_index.ae */

/* Note: ascii only */
JSValue js_string_toLowerCase(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int to_lower); /* ae/builtins_case.ae */

/* c < 128 */
static force_inline BOOL unicode_is_space_ascii(uint32_t c)
{
    return (c >= 0x0009 && c <= 0x000D) || (c == 0x0020);
}

int unicode_is_space_non_ascii(uint32_t c); /* ae/jshelpers.ae */

static force_inline BOOL unicode_is_space(uint32_t c)
{
    if (likely(c < 128)) {
        return unicode_is_space_ascii(c);
    } else {
        return unicode_is_space_non_ascii(c);
    }
}

JSValue js_string_trim(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_trim.ae */

JSValue js_string_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_string.ae */

JSValue js_string_repeat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_repeat.ae */

/**********************************************************************/

JSValue js_object_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_object.ae */

JSValue js_object_defineProperty(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_defprop.ae */

JSValue js_object_getPrototypeOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_object.ae */

/* 'obj' must be an object. 'proto' must be JS_NULL or an object */
JSValue js_set_prototype_internal(JSContext *ctx, JSValue obj, JSValue proto); /* ae/set_prototype.ae */

JSValue js_object_setPrototypeOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_object.ae */

JSValue js_object_create(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_ctor.ae */

JSValue js_object_keys(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_object.ae */

JSValue js_object_hasOwnProperty(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_object.ae */

JSValue js_object_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_object.ae */

/**********************************************************************/

JSValue js_error_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_error2.ae */

JSValue js_error_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_error.ae */

JSValue js_error_get_message(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_error.ae */

/**********************************************************************/

JSObject *js_get_array(JSContext *ctx, JSValue obj); /* ae/array_buffer.ae */

JSValue js_array_get_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

int js_array_resize(JSContext *ctx, JSValue *this_val, int new_len); /* ae/array_resize.ae */

JSValue js_array_set_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_push(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_unshift); /* ae/builtins_array.ae */

JSValue js_array_pop(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_shift(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_join(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_join.ae */

JSValue js_array_toString(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

int JS_IsArray(JSContext *ctx, JSValue obj); /* ae/misc_helpers.ae */

JSValue js_array_isArray(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_misc.ae */

JSValue js_array_reverse(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_concat(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_indexOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_lastIndexOf); /* ae/builtins_array.ae */

JSValue js_array_slice(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_splice(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_array.ae */

JSValue js_array_every(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int special); /* ae/builtins_iter.ae */

JSValue js_array_reduce(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int special); /* ae/builtins_iter.ae */

/* heapsort algorithm */
void rqsort_idx(size_t nmemb, int (*cmp)(size_t, size_t, void *), void (*swap)(size_t, size_t, void *), void *opaque); /* body in ae/rqsort.ae */

typedef struct {
    JSContext *ctx;
    BOOL exception;
    JSValue *parr;
    JSValue *pfunc;
} JSArraySortContext;

/* return -1, 0, 1  */
int js_array_sort_cmp(size_t i1, size_t i2, void *opaque); /* ae/array_sort_cmp.ae */

void js_array_sort_swap(size_t i1, size_t i2, void *opaque); /* ae/bc_sort_helpers.ae */

JSValue js_array_sort(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_iter.ae */

/**********************************************************************/

/* precondition: a and b are not NaN */
double js_fmin(double a, double b); /* ae/jshelpers.ae */

/* precondition: a and b are not NaN */
double js_fmax(double a, double b); /* ae/jshelpers.ae */

JSValue js_math_min_max(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_math.ae */

double js_math_sign(double a); /* ae/builtins_math.ae */

double js_math_fround(double a); /* ae/builtins_math.ae */

JSValue js_math_imul(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_misc.ae */

JSValue js_math_clz32(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_misc.ae */

JSValue js_math_atan2(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_math.ae */

JSValue js_math_pow(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_math.ae */

/* xorshift* random number generator by Marsaglia */
uint64_t xorshift64star(uint64_t *pstate); /* ae/jsutil2.ae */

JSValue js_math_random(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_math.ae */

/* typed array */

#define JS_TYPED_ARRAY_COUNT (JS_CLASS_FLOAT64_ARRAY - JS_CLASS_UINT8C_ARRAY + 1)

static uint8_t typed_array_size_log2[JS_TYPED_ARRAY_COUNT] = {
    0, 0, 0, 1, 1, 2, 2, 2, 3
};

int JS_ToIndex(JSContext *ctx, uint64_t *plen, JSValue val); /* ae/stack_ctor.ae */

JSValue js_array_buffer_alloc(JSContext *ctx, uint64_t len); /* ae/array_buffer.ae */

JSValue js_array_buffer_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_arraybuffer.ae */

JSValue js_array_buffer_get_byteLength(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_typedarray.ae */

JSValue js_typed_array_base_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_typedarray.ae */

JSValue js_typed_array_constructor_obj(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/typed_array_from_obj.ae */

JSValue js_typed_array_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_typedarray.ae */

JSObject *get_typed_array(JSContext *ctx, JSValue val); /* ae/builtins_typedarray.ae */

JSValue js_typed_array_get_length(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/builtins_typedarray.ae */

JSValue js_typed_array_subarray(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_typedarray.ae */

JSValue js_typed_array_set(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_typedarray.ae */

/* Date */

JSValue JS_NewDate(JSContext *ctx, double epoch_ms); /* ae/new_date.ae */

JSValue js_date_valueOf(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func.ae */

/* global */

JSValue js_global_eval(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_parse_entry.ae */

JSValue js_global_isNaN(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_misc.ae */

JSValue js_global_isFinite(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_misc.ae */

/* JSON */

JSValue js_json_parse(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_parse_entry.ae */

int js_to_quoted_string(JSContext *ctx, StringBuffer *b, JSValue str); /* ae/to_quoted_string.ae */

#define JSON_REC_SIZE 3

int check_circular_ref(JSContext *ctx, JSValue *stack_top, JSValue val); /* ae/check_circular_ref.ae */

/* XXX: no space nor replacer */
JSValue js_json_stringify(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_stringify.ae */

/**********************************************************************/
/* regexp */

typedef enum {
#define REDEF(id, size) REOP_ ## id,
#include "mquickjs_opcode.h"
#undef REDEF
    REOP_COUNT,
} REOPCodeEnum;

#define CAPTURE_COUNT_MAX 255
#define REGISTER_COUNT_MAX 255

typedef struct {
#ifdef DUMP_REOP
    const char *name;
#endif
    uint8_t size;
} REOpCode;

static const REOpCode reopcode_info[REOP_COUNT] = {
#ifdef DUMP_REOP
#define REDEF(id, size) { #id, size },
#else
#define REDEF(id, size) { size },
#endif
#include "mquickjs_opcode.h"
#undef REDEF
};

/* data accessor for the static-const reopcode_info[] table (each entry is
   one byte: the opcode size). */
const void *get_reopcode_info_table(void) { return reopcode_info; }

#define LRE_FLAG_GLOBAL     (1 << 0)
#define LRE_FLAG_IGNORECASE (1 << 1)
#define LRE_FLAG_MULTILINE  (1 << 2)
#define LRE_FLAG_DOTALL     (1 << 3)
#define LRE_FLAG_UNICODE    (1 << 4)
#define LRE_FLAG_STICKY     (1 << 5)

#define RE_HEADER_FLAGS          0
#define RE_HEADER_CAPTURE_COUNT  2
#define RE_HEADER_REGISTER_COUNT 3

#define RE_HEADER_LEN 4

#define CLASS_RANGE_BASE 0x40000000

typedef enum {
    CHAR_RANGE_d,
    CHAR_RANGE_D,
    CHAR_RANGE_s,
    CHAR_RANGE_S,
    CHAR_RANGE_w,
    CHAR_RANGE_W,
} CharRangeEnum;

int lre_get_capture_count(const uint8_t *bc_buf); /* ae/jshelpers.ae */

int lre_get_alloc_count(const uint8_t *bc_buf); /* ae/jshelpers.ae */

int lre_get_flags(const uint8_t *bc_buf); /* ae/jshelpers.ae */

#ifdef DUMP_REOP
static __maybe_unused void lre_dump_bytecode(const uint8_t *buf,
                                             int buf_len)
{
    int pos, len, opcode, bc_len, re_flags;
    uint32_t val, val2;

    assert(buf_len >= RE_HEADER_LEN);
    re_flags = lre_get_flags(buf);
    bc_len = buf_len - RE_HEADER_LEN;

    printf("flags: 0x%x capture_count=%d reg_count=%d bytecode_len=%d\n",
           re_flags, buf[RE_HEADER_CAPTURE_COUNT], buf[RE_HEADER_REGISTER_COUNT],
           bc_len);

    buf += RE_HEADER_LEN;

    pos = 0;
    while (pos < bc_len) {
        printf("%5u: ", pos);
        opcode = buf[pos];
        len = reopcode_info[opcode].size;
        if (opcode >= REOP_COUNT) {
            printf(" invalid opcode=0x%02x\n", opcode);
            break;
        }
        if ((pos + len) > bc_len) {
            printf(" buffer overflow (opcode=0x%02x)\n", opcode);
            break;
        }
        printf("%s", reopcode_info[opcode].name);
        switch(opcode) {
        case REOP_char1:
        case REOP_char2:
        case REOP_char3:
        case REOP_char4:
            {
                int i, n;
                n = opcode - REOP_char1 + 1;
                for(i = 0; i < n; i++) {
                    val = buf[pos + 1 + i];
                    if (val >= ' ' && val <= 126)
                        printf(" '%c'", val);
                    else
                        printf(" 0x%2x", val);
                }
            }
            break;
        case REOP_goto:
        case REOP_split_goto_first:
        case REOP_split_next_first:
        case REOP_lookahead:
        case REOP_negative_lookahead:
            val = get_u32(buf + pos + 1);
            val += (pos + 5);
            printf(" %u", val);
            break;
        case REOP_loop:
            val2 = buf[pos + 1];
            val = get_u32(buf + pos + 2);
            val += (pos + 6);
            printf(" r%u, %u", val2, val);
            break;
        case REOP_loop_split_goto_first:
        case REOP_loop_split_next_first:
        case REOP_loop_check_adv_split_goto_first:
        case REOP_loop_check_adv_split_next_first:
            {
                uint32_t limit;
                val2 = buf[pos + 1];
                limit = get_u32(buf + pos + 2);
                val = get_u32(buf + pos + 6);
                val += (pos + 10);
                printf(" r%u, %u, %u", val2, limit, val);
            }
            break;
        case REOP_save_start:
        case REOP_save_end:
        case REOP_back_reference:
        case REOP_back_reference_i:
            printf(" %u", buf[pos + 1]);
            break;
        case REOP_save_reset:
            printf(" %u %u", buf[pos + 1], buf[pos + 2]);
            break;
        case REOP_set_i32:
            val = buf[pos + 1];
            val2 = get_u32(buf + pos + 2);
            printf(" r%u, %d", val, val2);
            break;
        case REOP_set_char_pos:
        case REOP_check_advance:
            val = buf[pos + 1];
            printf(" r%u", val);
            break;
        case REOP_range8:
            {
                int n, i;
                n = buf[pos + 1];
                len += n * 2;
                for(i = 0; i < n * 2; i++) {
                    val = buf[pos + 2 + i];
                    printf(" 0x%02x", val);
                }
            }
            break;
        case REOP_range:
            {
                int n, i;
                n = get_u16(buf + pos + 1);
                len += n * 8;
                for(i = 0; i < n * 2; i++) {
                    val = get_u32(buf + pos + 3 + i * 4);
                    printf(" 0x%05x", val);
                }
            }
            break;
        default:
            break;
        }
        printf("\n");
        pos += len;
    }
}
#endif

void re_emit_op(JSParseState *s, int op); /* ae/re_emit.ae */

void re_emit_op_u8(JSParseState *s, int op, uint32_t val); /* ae/re_emit_helpers.ae */

void re_emit_op_u16(JSParseState *s, int op, uint32_t val); /* ae/re_emit_helpers.ae */

/* return the offset of the u32 value */
int re_emit_op_u32(JSParseState *s, int op, uint32_t val); /* ae/re_emit_helpers.ae */

int re_emit_goto(JSParseState *s, int op, uint32_t val); /* ae/re_emit.ae */

int re_emit_goto_u8(JSParseState *s, int op, uint32_t arg, uint32_t val); /* ae/re_emit_helpers.ae */

int re_emit_goto_u8_u32(JSParseState *s, int op, uint32_t arg0, uint32_t arg1, uint32_t val); /* ae/re_emit_helpers.ae */

void re_emit_char(JSParseState *s, int c); /* ae/re_emit.ae */

void re_parse_expect(JSParseState *s, int c); /* ae/re_emit_helpers.ae */

/* return JS_SHORTINT_MAX in case of overflow */
int parse_digits(const uint8_t **pp); /* ae/jshelpers.ae */

/* need_check_adv: false if the opcodes always advance the char pointer
   need_capture_init: true if all the captures in the atom are not set
*/
BOOL re_need_check_adv_and_capture_init(BOOL *pneed_capture_init,
                                               const uint8_t *bc_buf, int bc_buf_len); /* ae/re_need_check_adv.ae */

/* return the character or a class range (>= CLASS_RANGE_BASE) if inclass
   = TRUE */
int get_class_atom(JSParseState *s, BOOL inclass); /* ae/get_class_atom.ae */

/* code point ranges for Zs,Zl or Zp property */
static const uint16_t char_range_s[] = {
    0x0009, 0x000D + 1,
    0x0020, 0x0020 + 1,
    0x00A0, 0x00A0 + 1,
    0x1680, 0x1680 + 1,
    0x2000, 0x200A + 1,
    /* 2028;LINE SEPARATOR;Zl;0;WS;;;;;N;;;;; */
    /* 2029;PARAGRAPH SEPARATOR;Zp;0;B;;;;;N;;;;; */
    0x2028, 0x2029 + 1,
    0x202F, 0x202F + 1,
    0x205F, 0x205F + 1,
    0x3000, 0x3000 + 1,
    /* FEFF;ZERO WIDTH NO-BREAK SPACE;Cf;0;BN;;;;;N;BYTE ORDER MARK;;;; */
    0xFEFF, 0xFEFF + 1,
};

static const uint16_t char_range_w[] = {
    0x0030, 0x0039 + 1,
    0x0041, 0x005A + 1,
    0x005F, 0x005F + 1,
    0x0061, 0x007A + 1,
};

/* data accessors so the Aether regexp compiler can read the static
   char_range_s/_w tables (uint16_t entries). */
const void *get_char_range_s_table(void) { return char_range_s; }
int get_char_range_s_count(void) { return countof(char_range_s); }
const void *get_char_range_w_table(void) { return char_range_w; }
int get_char_range_w_count(void) { return countof(char_range_w); }



void re_emit_range_base(JSParseState *s, int c); /* ae/re_emit_range_base.ae */

int range_sort_cmp(size_t i1, size_t i2, void *opaque); /* ae/re_range_helpers.ae */

int range_sort_swap(size_t i1, size_t i2, void *opaque); /* ae/re_range_helpers.ae */

/* merge consecutive intervals, remove empty intervals and handle overlapping intervals */ 
int range_compress(uint8_t *tab, int len); /* ae/jshelpers.ae */

void re_range_optimize(JSParseState *s, int range_start, BOOL invert); /* ae/re_range_optimize.ae */

/* add the intersection of the two intervals and if offset != 0 the
   translated interval */
void add_interval_intersect(JSParseState *s,
                                   uint32_t start, uint32_t end,
                                   uint32_t start1, uint32_t end1,
                                   int offset); /* ae/re_range_helpers.ae */

void re_parse_char_class(JSParseState *s); /* ae/re_parse_char_class.ae */

void re_parse_quantifier(JSParseState *s, int last_atom_start, int last_capture_count); /* ae/re_parse_quantifier.ae */

/* return the number of bytes if char otherwise 0 */
int re_is_char(const uint8_t *buf, int start, int end); /* ae/re_is_char.ae */

int re_parse_alternative(JSParseState *s, int state, int dummy_param); /* ae/parse_re_alternative.ae */

int re_parse_disjunction(JSParseState *s, int state, int dummy_param); /* ae/parse_re_disjunction.ae */

/* Allocate the registers as a stack. The control flow is recursive so
   the analysis can be linear. */
int re_compute_register_count(JSParseState *s, uint8_t *bc_buf, int bc_buf_len); /* ae/re_register_count.ae */

/* return a JSByteArray. 'source' must be a string */
JSValue js_parse_regexp(JSParseState *s, int re_flags); /* ae/js_parse_regexp.ae */

/* regexp interpreter */

#define CP_LS   0x2028
#define CP_PS   0x2029

int is_line_terminator(uint32_t c); /* ae/jsutil2.ae */

int is_word_char(uint32_t c); /* ae/jsutil2.ae */

/* Note: we canonicalize as in the unicode case, but only handle ASCII characters */
int lre_canonicalize(uint32_t c); /* ae/jsutil2.ae */

#define GET_CHAR(c, cptr, cbuf_end)                          \
    do {                                                     \
        size_t clen;                                         \
        c = utf8_get(cptr, &clen);                           \
        cptr += clen;                                        \
    } while (0)

#define PEEK_CHAR(c, cptr, cbuf_end)                         \
    do {                                                                \
        size_t clen;                                         \
        c = utf8_get(cptr, &clen);                           \
    } while (0)

#define PEEK_PREV_CHAR(c, cptr, cbuf_start)                  \
    do {                                                     \
        const uint8_t *cptr1 = cptr - 1;                     \
        size_t clen;                                         \
        while ((*cptr1 & 0xc0) == 0x80)                                  \
            cptr1--;                                                     \
        c = utf8_get(cptr1, &clen);                                      \
    } while (0)

typedef enum {
    RE_EXEC_STATE_SPLIT,
    RE_EXEC_STATE_LOOKAHEAD,
    RE_EXEC_STATE_NEGATIVE_LOOKAHEAD,
} REExecStateEnum;

//#define DUMP_REEXEC

/* return 1 if match, 0 if not match or < 0 if error. str must be a
   JSString. capture_buf and byte_code are JSByteArray */
int lre_exec(JSContext *ctx, JSValue capture_buf,
                    JSValue byte_code, JSValue str, int cindex); /* ae/lre_exec.ae */

/* regexp js interface */

/* return the length */
size_t js_parse_regexp_flags(int *pre_flags, const uint8_t *buf); /* ae/regexp_flags.ae (body) */

/* pattern and flags must be strings */
JSValue js_compile_regexp(JSContext *ctx, JSValue pattern, JSValue flags); /* ae/compile_regexp.ae */

JSRegExp *js_get_regexp(JSContext *ctx, JSValue obj); /* ae/builtins_regexp.ae */

JSValue js_regexp_get_lastIndex(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_regexp.ae */

JSValue js_regexp_get_source(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_regexp.ae */

JSValue js_regexp_set_lastIndex(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_regexp.ae */

#define RE_FLAG_COUNT 6

/* return the string length */
size_t js_regexp_flags_str(char *buf, int re_flags); /* ae/regexp_flags.ae */

JSValue js_regexp_get_flags(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_regexp.ae */

JSValue js_regexp_constructor(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_regexp.ae */

enum {
    MAGIC_REGEXP_EXEC,
    MAGIC_REGEXP_TEST,
    MAGIC_REGEXP_SEARCH,
    MAGIC_REGEXP_FORCE_GLOBAL, /* same as exec but force the global flag */
};

JSValue js_regexp_exec(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int magic); /* ae/regexp_exec.ae */

/* if regexp replace: capture_buf != NULL, needle = NULL
   if string replace: capture_buf = NULL, captures_len = 1, needle != NULL
*/
int js_string_concat_subst(JSContext *ctx, StringBuffer *b, JSValue *str, JSValue *rep, uint32_t pos, uint32_t end_of_match, JSValue *capture_buf, uint32_t captures_len, JSValue *needle); /* ae/string_concat_subst.ae */

JSValue js_string_replace(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv, int is_replaceAll); /* ae/string_replace.ae */

// split(sep, limit)
JSValue js_string_split(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/string_split.ae */

JSValue js_string_match(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/string_match.ae */

JSValue js_string_search(JSContext *ctx, JSValue *this_val, int argc, JSValue *argv); /* ae/builtins_func.ae */
